version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    - image: circleci/mongo:4.0.0

    working_directory: /go/src/github.com/lab259/repository
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - deps-{{ .Branch }}-
            - deps-

      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 10s

      - run:
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      
      - run:
          name: Install ginkgo
          command: go get -u github.com/onsi/ginkgo/ginkgo
      
      - run:
          name: Get dependencies
          command: make dep-ensure

      - save_cache:
            key:  deps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            paths:
              - vendor

      - run:
          name: Run tests
          command: |
            make coverage-ci
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-results